name: demo

on:
  push:

jobs:
  demo:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: henrywhitaker3/ci-bump@main
        with:
          cmd: ci-bump yaml --patch '.versions.app' --minor '.versions.chart' --major '.versions.lock' demo.yaml

      - uses: stefanzweifel/git-auto-commit-action@v5
